steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/sample-cloudbuild:$REVISION_ID", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "eu.gcr.io/$PROJECT_ID/sample-cloudbuild:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - sampleapp-production
  - sampleapp=eu.gcr.io/$PROJECT_ID/sample-cloudbuild:$REVISION_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
substitutions:
  _ZONE: europe-west1-b # default value
  _CLUSTER: sample-cloudbuild